// <auto-generated />
using DemoCallAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoCallAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20221222144746_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoCallAPI.Models.Song", b =>
                {
                    b.Property<string>("SongId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Duration");

                    b.Property<string>("Singer");

                    b.Property<string>("Tittle");

                    b.HasKey("SongId");

                    b.HasIndex("SongId")
                        .IsUnique();

                    b.ToTable("Song");
                });
#pragma warning restore 612, 618
        }
    }
}
